defaults:
  - data: default
  - rollout: default
  - training: default
  - model: default
  - reward: verifiable
  - buffer: default
  - gpus: collocated
  - lora: disabled
  - wandb: default
  - eval: default
  - _self_

hydra:
  run:
    dir: .
